name: phone_number_validation
description: A test Flutter project for phone number validation.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: 0.25.0
  get_it: 5.0.6
  flutter_bloc: 6.1.1
  freezed: 0.12.7
  mask_text_input_formatter: 1.2.1

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg